version: "3"
services:
  web:
    image: web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./tmp/npm:/root/.npm:z
      - ./web/src:/usr/src/app/src:z
    ports:
      - "3000:3000"
